name: make-ubuntu

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build with make
      run: make
    - name: Extract current branch name
      shell: bash
      run: ref="${GITHUB_REF#refs/heads/}" && echo "::set-output name=branch::${ref////-}"
      id: ref
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: minecyper-artifacts-${{ steps.ref.outputs.branch }}
        path: |
          MineCYper
          LICENSE
